export const CapitalAdjustmentActions={
    //=====create capital adjustment price======
    //get list
    GET_LIST_PRODUCT:'GET_LIST_PRODUCT',
    SET_LOADING_GET_LIST_PRODUCT :'SET_LOADING_GET_LIST_PRODUCT',
    FORM_SELECTED_SEARCH_PRODUCT: 'FORM_SELECTED_SEARCH_PRODUCT',
    VALIDATE_CREATE_CAPITAL_ADJUSTMENT:'VALIDATE_CREATE_CAPITAL_ADJUSTMENT',
    GET_EXTRA_INFO_CAPITAL_ADJUSTMENT:'GET_EXTRA_INFO_CAPITAL_ADJUSTMENT',
    OPEN_MODAL_CONFIRM_CAPITAL_ADJUSTMENT:'OPEN_MODAL_CONFIRM_CAPITAL_ADJUSTMENT',
    //=====end create capital adjustment price=====



    //=====Capital adjustment list======
    FILTER_ADVANCED_SEARCH_UPDATE: 'FILTER_ADVANCED_SEARCH_UPDATE',
    FILTER_ADVANCED_EMPLOYEE_CREATE_UPDATE: 'FILTER_ADVANCED_EMPLOYEE_CREATE_UPDATE',
    FILTER_ADVANCED_EMPLOYEE_CREATE_VALUE_CHANGE: 'FILTER_ADVANCED_EMPLOYEE_CREATE_VALUE_CHANGE',
    FILTER_ADVANCED_EMPLOYEE_CREATE_TAB_UPDATE: 'FILTER_ADVANCED_EMPLOYEE_CREATE_TAB_UPDATE',
    FILTER_ADVANCED_EMPLOYEE_CREATE_KEYWORD_UPDATE: 'FILTER_ADVANCED_EMPLOYEE_CREATE_KEYWORD_UPDATE',
    FILTER_ADVANCED_EMPLOYEE_CREATE_DATE_TIME_UPDATE: 'FILTER_ADVANCED_EMPLOYEE_CREATE_DATE_TIME_UPDATE',
    FILTER_ADVANCED_EMPLOYEE_CREATE_ACTIVE_UPDATE: 'FILTER_ADVANCED_EMPLOYEE_CREATE_ACTIVE_UPDATE',
    FILTER_ADVANCED_STATUS_STATE_UPDATE: 'FILTER_ADVANCED_STATUS_STATE_UPDATE',

    TABLE_UPDATE_DISPLAY_LIST: 'TABLE_UPDATE_DISPLAY_LIST',
  TABLE_UPDATE_DISPLAY_LIST_ORIGIN: 'TABLE_UPDATE_DISPLAY_LIST_ORIGIN',
    TABLE_UPDATE_PAGINATION: 'TABLE_UPDATE_PAGINATION',
    TABLE_SELECTED_LIST_UPDATE: 'TABLE_SELECTED_LIST_UPDATE',

    TABLE_DISPLAY_DETAIL_UPDATE: 'TABLE_DISPLAY_DETAIL_UPDATE',
    TABLE_DISPLAY_DETAIL_ID_UPDATE: 'TABLE_DISPLAY_DETAIL_ID_UPDATE',

    MODAL_CANCEL_BILL_UPDATE: 'MODAL_CANCEL_BILL_UPDATE',
    MODAL_APPROVE_BILL_UPDATE: 'MODAL_APPROVE_BILL_UPDATE',
    //=====end Capital adjustment list======
}