export const actionTypes = {
  ORIGIN: 'ORIGIN',
  RESET_FORM_DEFAULT: 'RESET_FORM_DEFAULT',
  // general info
  FORM_WAREHOUSE_EXPORT_UPDATE: 'FORM_WAREHOUSE_EXPORT_UPDATE',
  FORM_WAREHOUSE_IMPORT_UPDATE: 'FORM_WAREHOUSE_IMPORT_UPDATE',
  FORM_WAREHOUSE_KEYWORD_UPDATE: 'FORM_WAREHOUSE_KEYWORD_UPDATE',
  FORM_WAREHOUSE_LIST_UPDATE: 'FORM_WAREHOUSE_LIST_UPDATE',
  // product info
  FORM_PRODUCT_UPDATE: 'FORM_PRODUCT_UPDATE',
  FORM_PRODUCT_LIST_UPDATE: 'FORM_PRODUCT_LIST_UPDATE',
  FORM_PRODUCT_LOADING_UPDATE: 'FORM_PRODUCT_LOADING_UPDATE',
  FORM_PRODUCT_SELECTED_LIST_UPDATE: 'FORM_PRODUCT_SELECTED_LIST_UPDATE',
  // extra info
  FORM_NOTE_UPDATE: 'FORM_NOTE_UPDATE',
  FORM_EXTRA_INFO_UPDATE: 'FORM_EXTRA_INFO_UPDATE',
  // VALIDATE
  SET_VALIDATE_FORM: 'SET_VALIDATE_FORM',
  RESET_FORM: 'RESET_FORM',
  UPDATE_LOADING: 'UPDATE_LOADING',
  SET_FORM_VALID: 'SET_FORM_VALID',
  // CREATE WAREHOUSE MODAL 
  SET_CREATE_MODAL: 'SET_CREATE_MODAL',
  SET_CREATE_MODAL_ADDRESS: 'SET_CREATE_MODAL_KEYWORD',
  SET_CREATE_MODAL_ADDRESS_PROVINCE_KEYWORD: 'SET_CREATE_MODAL_ADDRESS_PROVINCE_KEYWORD',
  SET_CREATE_MODAL_ADDRESS_DISTRICT_KEYWORD: 'SET_CREATE_MODAL_ADDRESS_DISTRICT_KEYWORD',
  SET_CREATE_MODAL_ADDRESS_WARD_KEYWORD: 'SET_CREATE_MODAL_ADDRESS_WARD_KEYWORD',
  // INFO MODAL
  SET_MODAL_INFO: 'SET_MODAL_INFO',
}
