export const SCRIPT = {
  CUS_INFO: "Thông tin khách hàng",
  CUS_MINISTERIAL: "Thông tin bổ trợ",
  CUS_ID: "Mã khách hàng",
  PL_CUS_ID: "Nhập mã khách hàng (ví dụ: KH220815...)",
  TT_CODE: "Trường hợp bạn không nhập mã khách hàng, Evoshop sẽ tự động sinh theo mã hệ thống.",
  CUS_NAME: "Tên khách hàng",
  PL_CUS_NAME: "Nhập tên khách hàng",
  CUS_PHONE: "Số điện thoại",
  PL_CUS_PHONE: "Nhập số điện thoại khách hàng",
  CUS_EMAIL: "Email",
  PL_CUS_EMAIL: "Nhập email khách hàng",
  CUS_ADDRESS: "Địa chỉ đầy đủ",
  PL_CUS_ADDRESS: "Nhập địa chỉ đầy đủ",
  MALE: "Nam",
  FEMALE: "Nữ",
  ADDRESS_SEPARATION: "Tách địa chỉ",
  SE_CUS_CITY: "Tỉnh/Thành phố",
  SE_CUS_DISTRICT: "Quận/Huyện",
  SE_CUS_WARD: "Phường/Xã",
  GROUP_EMPLOYEE: "Nhóm khách hàng",
  SE_GROUP_EMPLOYEE: "Chọn nhóm khách hàng",
  CREATE_GROUP_EMPLOYEE: "Thêm nhóm khách hàng",
  PRICE_POLICY: "Chính sách giá",
  WHOLESALE_PRICE: "Giá bán sỉ",
  RETAIL_PRICE: "Giá bán lẻ",
  SE_PRICE_POLICY: "Chọn chính sách giá",
  ACTIVE_INACTIVE:"Kích hoạt/Ngưng kích hoạt khách hàng",
  T_CANCEL: "Hủy",
  T_SAVE: "Lưu",
  UPDATE_SUCCESS: "Cập nhập khách hàng thành công.",
  UPDATE_FAIL: "Cập nhập khách hàng thất bại!",

  VALIDATE: {
    GROUP_CUSTOMER_ID : "Mã nhóm khách hàng không được bỏ trống!",
    GROUP_CUSTOMER_NAME : "Tên nhóm khách hàng không được bỏ trống!",
    EMPTY_NAME: "Tên khách hàng không được bỏ trống!",
    EMPTY_EMAIL: "Email không được bỏ trống!",
    EMPTY_PHONE: "Số điện thoại không được bỏ trống!",
    MIN_PHONE: "Số điện thoại tối thiểu 10 số!",
    EMPTY_ADDRESS: "Địa chỉ không được bỏ trống!",
    INVALID_EMAIL: "Vui lòng nhập đúng định dạng email!",
    INVALID_CITY: "Vui lòng chọn tỉnh/thành phố!",
    INVALID_DISTRICT: "Vui lòng chọn quận/huyện!",
    INVALID_WARD: "Vui lòng chọn phường/xã!",
    INVALID_CODE: "Vui lòng không nhập dấu, khoảng cách và ký tự đặc biệt!!",
    INVALID_WHITESPACE_AT_BEGINNING_AND_END: "Vui lòng không nhập dấu cách ở đầu hoặc cuối!",
    INVALID_PHONE: "Vui lòng nhập đúng số điện thoại!",
    INVALID_SEPARATE: "evoshop chưa nhận diện được địa chỉ này, hãy kiểm tra lại hoặc tự chọn địa chỉ ở bên dưới bạn nhé!",
  }
}