import {DISPLAY_NAME_MENU} from "../../../const/display_name_menu";

export const SCRIPT = {
  BREADCRUMB: {
    TITLE: DISPLAY_NAME_MENU.PRINT_PAGE.SET_FORM,
    SETTING: DISPLAY_NAME_MENU.CONFIG_AND_SETTING_PAGE.HEADER,
    VIEW: DISPLAY_NAME_MENU.PRINT_PAGE.VIEW_FORM
  },
  FILTER: {
    TYPE: {
      LABEL: DISPLAY_NAME_MENU.PRINT_PAGE.CHOOSE_PRINT,
      EMPTY: DISPLAY_NAME_MENU.PRINT_PAGE.PATTERN_NOT_FOUND,
    },
    SIZE: {
      LABEL: DISPLAY_NAME_MENU.PRINT_PAGE.CHOOSE_PRINT_SIZE,
      EMPTY: DISPLAY_NAME_MENU.PRINT_PAGE.PRINT_SIZE_NOT_FOUND,
    },
  },
  GROUP_BUTTON: {
    EDIT: DISPLAY_NAME_MENU.GENERAL.EDIT,
    PRINT: DISPLAY_NAME_MENU.PRINT_PAGE.TEST_PRINT,
    CANCEL: DISPLAY_NAME_MENU.GENERAL.CANCEL,
    SAVE: DISPLAY_NAME_MENU.GENERAL.SAVE,
    CONFIRM: DISPLAY_NAME_MENU.GENERAL.CONFIRM,
  },
  TITLE: DISPLAY_NAME_MENU.GENERAL.PRINTED_FORM,
  PREVIEW: DISPLAY_NAME_MENU.GENERAL.PREVIEW,
  DEFAULT_TEMPLATE: DISPLAY_NAME_MENU.PRINT_PAGE.EVO_TEMPLATE,
  SELECT_KEYWORD: DISPLAY_NAME_MENU.PRINT_PAGE.CHOOSE_KEYWORD,
  MODAL: {
    TITLE: DISPLAY_NAME_MENU.PRINT_PAGE.KEYWORD_LIST,
    SUB_TITLE: DISPLAY_NAME_MENU.PRINT_PAGE.MODAL_SUBTITLE,
    CHOOSE: DISPLAY_NAME_MENU.GENERAL.CHOOSE,
  },
  CATEGORIES: {
    INFO_STORE: DISPLAY_NAME_MENU.GENERAL.STORE_INFO,
    INFO_ORDER:  DISPLAY_NAME_MENU.GENERAL.ORDER_INFO,
    INFO_VOUCHER: DISPLAY_NAME_MENU.GENERAL.RECEIPT_AND_PAYMENT,
    INFO_INVENTORY: DISPLAY_NAME_MENU.GENERAL.INVENTORY_CHECK_INFO,
    INFO_PURCHASE_ORDER: DISPLAY_NAME_MENU.GENERAL.ADMISSION_INFO,
    TTS: 'Tiktok Shop',
  },
  TITLE_CONFIRM_UPOS: DISPLAY_NAME_MENU.PRINT_PAGE.USE_EVO_TEMPLATE,
  CONFIRM_TEMPLATE: DISPLAY_NAME_MENU.PRINT_PAGE.CONFIRM_TEMPLATE,
  TITLE_CONFIRM_QUIT: DISPLAY_NAME_MENU.GENERAL.CONFIRM_LEAVING,
  CONFIRM_QUIT: DISPLAY_NAME_MENU.GENERAL.CONFIRM_LEAVING_CONTENT,
}