export const bulkOrderActions = {
  FILTER_DATE_TIME_UPDATE: 'FILTER_DATE_TIME_UPDATE',
  FILTER_DATE_TIME_TRIGGER_UPDATE: 'FILTER_DATE_TIME_TRIGGER_UPDATE',
  FILTER_EMPLOYEE_UPDATE: 'FILTER_EMPLOYEE_UPDATE',
  FILTER_EMPLOYEE_KEYWORD_UPDATE: 'FILTER_EMPLOYEE_KEYWORD_UPDATE',
  FILTER_ORIGIN_UPDATE: 'FILTER_ORIGIN_UPDATE',
  FILTER_OTHER_ACTIVE_VALUE_UPDATE: 'FILTER_OTHER_ACTIVE_VALUE_UPDATE',
  FILTER_SEARCH_UPDATE: 'FILTER_SEARCH_UPDATE',
  FILTER_SHIPPING_PARTNER_UPDATE: 'FILTER_SHIPPING_PARTNER_UPDATE',
  FILTER_SHIPPING_PARTNER_KEYWORD_UPDATE:
    'FILTER_SHIPPING_PARTNER_KEYWORD_UPDATE',
  FILTER_TAG_DELETE: 'FILTER_TAG_DELETE',
  TABLE_UPDATE: 'TABLE_UPDATE',
  TABLE_DISPLAY_LOADING_UPDATE: 'TABLE_DISPLAY_LOADING_UPDATE',
  TABLE_UPDATE_ONLY_ERROR: 'TABLE_UPDATE_ONLY_ERROR',
}

export const bulkOrderCreateActions = {
  FORM_ORIGIN_UPDATE: 'FORM_ORIGIN_UPDATE',
  FORM_SOURCE_KEYWORD_UPDATE: 'FORM_SOURCE_KEYWORD_UPDATE',
  FORM_SOURCE_UPDATE: 'FORM_SOURCE_UPDATE',
  FORM_SHIPPING_PARTNER_UPDATE: 'FORM_SHIPPING_PARTNER_UPDATE',
  FORM_SHIPPING_PARTNER_KEYWORD_UPDATE: 'FORM_SHIPPING_PARTNER_KEYWORD_UPDATE',
  FORM_SHIPPING_PARTNER_OPTION_UPDATE: 'FORM_SHIPPING_PARTNER_OPTION_UPDATE',
  FORM_SHIPPING_POINT_UPDATE: 'FORM_SHIPPING_POINT_UPDATE',
  FORM_SHIPPING_POINT_KEYWORD_UPDATE: 'FORM_SHIPPING_POINT_KEYWORD_UPDATE',
  FORM_SHIPPING_POINT_LIST_UPDATE: 'FORM_SHIPPING_POINT_LIST_UPDATE',
  TABLE_DISPLAY_UPDATE: 'TABLE_DISPLAY_UPDATE',
  TABLE_ERROR_UPDATE: 'TABLE_ERROR_UPDATE',
  TABLE_DISPLAY_LOADING_UPDATE: 'TABLE_DISPLAY_LOADING_UPDATE',
  TABLE_SELECTED_UPDATE: 'TABLE_SELECTED_UPDATE',
  SETLOADINGPERCENT: 'SETLOADINGPERCENT',
}
