export const miniGameAction = {
    //get detail list customer
    GET_DETAIL_SETTING_MINI_GAME:'GET_DETAIL_SETTING_MINI_GAME',
    GET_LIST_CUSTOMER_MINI_GAME:'GET_LIST_CUSTOMER_MINI_GAME',
    GET_DETAIL_SETTING_CONDITION:'GET_DETAIL_SETTING_CONDITION',



    //setting mini game
    OPEN_MODAL_SETTING_MINI_GAME:'OPEN_MODAL_SETTING_MINI_GAME',
    SETTING_CONDITION_MINI_GAME:'SETTING_CONDITION_MINI_GAME',
    SET_START_DATE_TIME:'SET_START_DATE_TIME',
    SETTING_MINI_GAME_TIME:'SETTING_MINI_GAME_TIME',
    RESET_SETTING_MINI_GAME:'RESET_SETTING_MINI_GAME',
    SET_SUBMIT_BUTTON:'SET_SUBMIT_BUTTON',


    //modal winner
    OPEN_MODAL_WINNER:"OPEN_MODAL_WINNER",
    GET_LIST_WINNER_MINI_GAME:'GET_LIST_WINNER_MINI_GAME',
    GET_DETAIL_WINNER_MINI_GAME:'GET_DETAIL_WINNER_MINI_GAME',

    //loading update comment
    SET_LOADING_UPDATE_COMMENT:'SET_LOADING_UPDATE_COMMENT',

}