export const facebookFanpageActions = {
  FANPAGE_LIST_UPDATE: 'FANPAGE_LIST_UPDATE',
  FANPAGE_SELECTED_UPDATE: 'FANPAGE_SELECTED_UPDATE',
  FILTER_CONNECTED_TOGGLE: 'FILTER_CONNECTED_TOGGLE',
  MODAL_ID_UPDATE: 'MODAL_ID_UPDATE',
  SET_LOADING: 'SET_LOADING',
}
