export const PaymentManagementActions={
    //=================== Create payment ===========
    //EDIT
    GET_DETAIL_EDIT_PAYMENT :'GET_DETAIL_EDIT_PAYMENT',


    GET_LIST_RECIPIENT_PERSON:'GET_LIST_RECIPIENT_PERSON',
    FORM_PAYMENT_RICIPIENT_GROUP_UPDATE:'FORM_PAYMENT_RICIPIENT_GROUP_UPDATE',
    GET_KEYWORD_RECIPIENT_GROUP_UPDATE:'GET_KEYWORD_RECIPIENT_GROUP_UPDATE',
    UPLOAD_CAN_LOAD_MORE:'UPLOAD_CAN_LOAD_MORE',
    GET_KEYWORD_RECIPIENT_PERSON_UPDATE:'GET_KEYWORD_RECIPIENT_PERSON_UPDATE',
    GET_RECIPIENT_PERSON_UPDATE:'GET_RECIPIENT_PERSON_UPDATE',

    //payment type
    GET_LIST_PAYMENT_TYPE:'GET_LIST_PAYMENT_TYPE',
    UPDATE_PAYMENT_TYPE:'UPDATE_PAYMENT_TYPE',
    UPLOAD_CAN_LOAD_MORE_PAYMENT_TYPE:'UPLOAD_CAN_LOAD_MORE_PAYMENT_TYPE',
    SEARCH_PAYMENT_TYPE:'SEARCH_PAYMENT_TYPE',
    //payment method
    GET_LIST_PAYMENT_METHOD:'GET_LIST_PAYMENT_METHOD',
    UPDATE_PAYMENT_METHOD:'UPDATE_PAYMENT_METHOD',
    UPLOAD_CAN_LOAD_MORE_PAYMENT_METHOD:'UPLOAD_CAN_LOAD_MORE_PAYMENT_METHOD',
    SEARCH_PAYMENT_METHOD:'SEARCH_PAYMENT_METHOD',
    FORM_PAYMENT_DATETIME_UPDATE:'FORM_PAYMENT_DATETIME_UPDATE',
    GET_PAYMENT_CODE_UPDATE:"GET_PAYMENT_CODE_UPDATE",
    GET_PAYMENT_VALUE_UPDATE:"GET_PAYMENT_VALUE_UPDATE",
    GET_DESCRIPTION_UPDATE:"GET_DESCRIPTION_UPDATE",
    GET_REFERENCE_UPDATE:"GET_REFERENCE_UPDATE",

    //modal
    OPEN_MODAL_ADD_NEW:'OPEN_MODAL_ADD_NEW',
    GET_ADD_NEW_PAYMENT:'GET_ADD_NEW_PAYMENT',
    GET_DETAIL_PAYMENT_TYPE:"GET_DETAIL_PAYMENT_TYPE",
    OPEN_MODAL_PAYMENT_TYPE:'OPEN_MODAL_PAYMENT_TYPE',
    SET_DETAIL_EMPTY:'SET_DETAIL_EMPTY',
    SET_HAVE_EDIT:'SET_HAVE_EDIT',
    MODAL_FORM_CREATE:'MODAL_FORM_CREATE',
    //validate
    VALIDATE_FORM_CREATE_PAYMENT:'VALIDATE_FORM_CREATE_PAYMENT',
    VALIDATE_DETAIL_PAYMENT_TYPE:'VALIDATE_DETAIL_PAYMENT_TYPE',
    //=================== Create payment ===========

    //=====table====

    // FILTER
    FILTER_DATE_TIME_UPDATE: 'FILTER_DATE_TIME_UPDATE',
    FILTER_DATE_TIME_TRIGGER_UPDATE: 'FILTER_DATE_TIME_TRIGGER_UPDATE',
    FILTER_ACTIVE_DATE_TIME_UPDATE: 'FILTER_ACTIVE_DATE_TIME_UPDATE',

    FILTER_OTHER_PAYMENT_METHOD: 'FILTER_OTHER_PAYMENT_METHOD',
    FILTER_OTHER_PAYMENT_METHOD_CHANGE_KEYWORD: 'FILTER_OTHER_PAYMENT_METHOD_CHANGE_KEYWORD',
    FILTER_OTHER_PAYMENT_METHOD_UPDATE_VALUE: 'FILTER_OTHER_PAYMENT_METHOD_UPDATE_VALUE',
    FILTER_OTHER_PAYMENT_METHOD_TAB_UPDATE: 'FILTER_OTHER_PAYMENT_METHOD_TAB_UPDATE',
    FILTER_ACTIVE_OTHER_PAYMENT_METHOD_UPDATE: 'FILTER_ACTIVE_OTHER_PAYMENT_METHOD_UPDATE',

    FILTER_OTHER_GROUP_SUBMITTER: 'FILTER_OTHER_GROUP_SUBMITTER',
    FILTER_OTHER_GROUP_SUBMITTER_CHANGE_KEYWORD: 'FILTER_OTHER_GROUP_SUBMITTER_CHANGE_KEYWORD',
    FILTER_OTHER_GROUP_SUBMITTER_UPDATE_LIST: 'FILTER_OTHER_GROUP_SUBMITTER_UPDATE_LIST',
    FILTER_OTHER_GROUP_SUBMITTER_UPDATE_VALUE: 'FILTER_OTHER_GROUP_SUBMITTER_UPDATE_VALUE',
    FILTER_ACTIVE_OTHER_GROUP_SUBMITTER_UPDATE: 'FILTER_ACTIVE_OTHER_GROUP_SUBMITTER_UPDATE',

    FILTER_OTHER_EMPLOYEE_CREATE: 'FILTER_OTHER_EMPLOYEE_CREATE',
    FILTER_OTHER_EMPLOYEE_CREATE_CHANGE_KEYWORD: 'FILTER_OTHER_EMPLOYEE_CREATE_CHANGE_KEYWORD',
    FILTER_OTHER_EMPLOYEE_CREATE_UPDATE_VALUE: 'FILTER_OTHER_EMPLOYEE_CREATE_UPDATE_VALUE',
    FILTER_OTHER_EMPLOYEE_CREATE_TAB_UPDATE: 'FILTER_OTHER_EMPLOYEE_CREATE_TAB_UPDATE',
    FILTER_ACTIVE_OTHER_EMPLOYEE_CREATE_UPDATE: 'FILTER_ACTIVE_OTHER_EMPLOYEE_CREATE_UPDATE',

    FILTER_OTHER_TYPE_RECEIPT: 'FILTER_OTHER_TYPE_RECEIPT',
    FILTER_OTHER_TYPE_RECEIPT_CHANGE_KEYWORD: 'FILTER_OTHER_TYPE_RECEIPT_CHANGE_KEYWORD',
    FILTER_OTHER_TYPE_RECEIPT_UPDATE_VALUE: 'FILTER_OTHER_TYPE_RECEIPT_UPDATE_VALUE',
    FILTER_OTHER_TYPE_RECEIPT_TAB_UPDATE: 'FILTER_OTHER_TYPE_RECEIPT_TAB_UPDATE',
    FILTER_ACTIVE_OTHER_TYPE_RECEIPT_UPDATE: 'FILTER_ACTIVE_OTHER_TYPE_RECEIPT_UPDATE',

    FILTER_ACTIVE_OTHER_STATUS: 'FILTER_ACTIVE_OTHER_STATUS',
    FILTER_CHANGE_SEARCH_KEYWORD: 'FILTER_CHANGE_SEARCH_KEYWORD',
    // END FILTER


    // TABLE
    TABLE_DISPLAY_DATA_UPDATE: 'TABLE_DISPLAY_DATA_UPDATE',
    TABLE_DISPLAY_DETAIL_UPDATE: 'TABLE_DISPLAY_DETAIL_UPDATE',
    TABLE_DISPLAY_DETAIL_ID_UPDATE: 'TABLE_DISPLAY_DETAIL_ID_UPDATE',
    TABLE_PAGINATION_UPDATE: 'TABLE_PAGINATION_UPDATE',

    TOGGLE_MODAL_EDIT_DESCRIPTION: 'TOGGLE_MODAL_EDIT_DESCRIPTION',
    UPDATE_MODAL_EDIT_DESCRIPTION: 'UPDATE_MODAL_EDIT_DESCRIPTION',
    TOGGLE_MODAL_CANCEL_RECEIPT: 'TOGGLE_MODAL_CANCEL_RECEIPT',
    // END TABLE
}