export const InventoryAction = {
    FOCUS_INPUT: 'FOCUS_INPUT',
    //  FILTER
    FILTER_ADVANCED_SEARCH_UPDATE: 'FILTER_ADVANCED_SEARCH_UPDATE',
    FILTER_DATE_TIME_UPDATE: 'FILTER_DATE_TIME_UPDATE',
    FILTER_ACTIVE_DATE_TIME_UPDATE: 'FILTER_ACTIVE_DATE_TIME_UPDATE',
    FILTER_PRINT_UPDATE: 'FILTER_PRINT_UPDATE',
    FILTER_EMPLOYEE_UPDATE: 'FILTER_EMPLOYEE_UPDATE',
    FILTER_EMPLOYEE_CATEGORY_UPDATE: 'FILTER_EMPLOYEE_CATEGORY_UPDATE',
    FILTER_EMPLOYEE_KEYWORD_UPDATE: 'FILTER_EMPLOYEE_KEYWORD_UPDATE',
    FILTER_EMPLOYEE_TAB_UPDATE: 'FILTER_EMPLOYEE_TAB_UPDATE',
    FILTER_SEARCH_UPDATE: 'FILTER_SEARCH_UPDATE',
    FILTER_SHIPPING_STATUS_TAB_UPDATE: 'FILTER_SHIPPING_STATUS_TAB_UPDATE',
    FILTER_SHIPPING_STATUS_UPDATE: 'FILTER_SHIPPING_STATUS_UPDATE',
    FILTER_SHIPPING_STATUS_LIST_UPDATE: 'FILTER_SHIPPING_STATUS_LIST_UPDATE',
    FILTER_PRINT_KEYWORD_UPDATE: 'FILTER_PRINT_KEYWORD_UPDATE',
    FILTER_ORIGIN_DATA_UPDATE: 'FILTER_ORIGIN_DATA_UPDATE',
    FILTER_WAREHOUSE_KEYWORD_UPDATE: 'FILTER_WAREHOUSE_KEYWORD_UPDATE',
    FILTER_WAREHOUSE_UPDATE: 'FILTER_WAREHOUSE_UPDATE',
    OTHER_FILTER_APPLY: 'OTHER_FILTER_APPLY',
    TAG_FILTER_DELETE: 'TAG_FILTER_DELETE',
    // NOTIFICATIONS
    NOTIFICATIONS_LIST_UPDATE: 'NOTIFICATIONS_LIST_UPDATE',
    // PANELS
    PANELS_UPDATE: 'PANELS_UPDATE',
    // TABLE
    TABLE_DISPLAY_DATA_UPDATE: 'TABLE_DISPLAY_DATA_UPDATE',
    TABLE_DISPLAY_DETAIL_UPDATE: 'TABLE_DISPLAY_DETAIL_UPDATE',
    TABLE_AMOUNT_UPDATE:'TABLE_AMOUNT_UPDATE',
    TABLE_PAGINATION_UPDATE: 'TABLE_PAGINATION_UPDATE',
    TABLE_SELECTED_LIST_UPDATE: 'TABLE_SELECTED_LIST_UPDATE',
    TABLE_PAGINATE_DATA:'TABLE_PAGINATE_DATA',
    TABLE_DISPLAY_LOADING_UPDATE:'TABLE_DISPLAY_LOADING_UPDATE',
    //Modal confirm
    OPEN_MODAL_CONFIRM:'OPEN_MODAL_CONFIRM',
    FILTER_DATE_TIME_TRIGGER_UPDATE:'FILTER_DATE_TIME_TRIGGER_UPDATE',
    //Import
    IMPORT_FILE:'IMPORT_FILE',
}