export const PaymentTypeActions={
    GET_LIST_PAYMENT_TYPE:'GET_LIST_PAYMENT_TYPE',
    TABLE_PAGINATE_DATA:'TABLE_PAGINATE_DATA',
    //pagination
    TABLE_AMOUNT_UPDATE:'TABLE_AMOUNT_UPDATE',
    TABLE_PAGINATION_UPDATE: 'TABLE_PAGINATION_UPDATE',

    //detail payment
    GET_DETAIL_PAYMENT_TYPE:'GET_DETAIL_PAYMENT_TYPE',
    SET_DETAIL_EMPTY:'SET_DETAIL_EMPTY',
    SET_FORM_CREATE:'SET_FORM_CREATE',


    //validate
    VALIDATE_DETAIL_PAYMENT_TYPE:'VALIDATE_DETAIL_PAYMENT_TYPE',

    SET_LOADING_PAYMENT_TYPE:'SET_LOADING_PAYMENT_TYPE',
    OPEN_MODAL_PAYMENT_TYPE:'OPEN_MODAL_PAYMENT_TYPE',

    GET_ID:'GET_ID',
    SET_HAVE_EDIT:'SET_HAVE_EDIT',
    SET_SEARCH_PAYMENT_TYPE:'SET_SEARCH_PAYMENT_TYPE',

    //check box
    SET_IS_CHECK_BOX:'SET_IS_CHECK_BOX',
    SET_COUNT:'SET_COUNT',
    SET_ACTIVE_CHECK_BOX:'SET_ACTIVE_CHECK_BOX',

    //confirm
    GET_LIST_AFTER_CONFIRM : 'GET_LIST_AFTER_CONFIRM',

}