export const facebookLivestreamScriptActions = {
  FANPAGE_LIST_ORIGIN_UPDATE: 'FANPAGE_LIST_ORIGIN_UPDATE',
  FANPAGE_SEARCH_UPDATE: 'FANPAGE_SEARCH_UPDATE',
  FANPAGE_KEYWORD_UPDATE: 'FANPAGE_KEYWORD_UPDATE',
  FANPAGE_TAB_UPDATE: 'FANPAGE_TAB_UPDATE',
  FANPAGE_VALUE_UPDATE: 'FANPAGE_VALUE_UPDATE',
  SCRIPT_LIST_UPDATE: 'SCRIPT_LIST_UPDATE',
  SCRIPT_LOADING_UPDATE: 'SCRIPT_LOADING_UPDATE',
}
