export const currentPageActions = {
  FORM_ADDRESS_UPDATE: 'FORM_ADDRESS_UPDATE',
  FORM_ADDRESS_PROVINCE_KEYWORD_UPDATE: 'FORM_ADDRESS_PROVINCE_KEYWORD_UPDATE',
  FORM_ADDRESS_PROVINCE_UPDATE: 'FORM_ADDRESS_PROVINCE_UPDATE',
  FORM_ADDRESS_PROVINCE_RESET: 'FORM_ADDRESS_PROVINCE_RESET',
  FORM_ADDRESS_DISTRICT_KEYWORD_UPDATE: 'FORM_ADDRESS_DISTRICT_KEYWORD_UPDATE',
  FORM_ADDRESS_DISTRICT_UPDATE: 'FORM_ADDRESS_DISTRICT_UPDATE',
  FORM_ADDRESS_WARD_KEYWORD_UPDATE: 'FORM_ADDRESS_WARD_KEYWORD_UPDATE',
  FORM_ADDRESS_WARD_UPDATE: 'FORM_ADDRESS_WARD_UPDATE',
  SET_USER_SUGGEST_ADDRESS: 'SET_USER_SUGGEST_ADDRESS',
  SET_VALIDATE_FORM: 'SET_VALIDATE_FORM',
}
