
export const typeReceiptActions = {
  //  FILTER
  FILTER_ADVANCED_SEARCH_UPDATE: 'FILTER_ADVANCED_SEARCH_UPDATE',
  TABLE_UPDATE_DISPLAY_LIST: 'TABLE_UPDATE_DISPLAY_LIST',
  TABLE_UPDATE_PAGINATION: 'TABLE_UPDATE_PAGINATION',
  TABLE_SELECTED_LIST_UPDATE: 'TABLE_SELECTED_LIST_UPDATE',

  // MODAL
  MODAL_CREATE_RECEIPT_TOGGLE_OPEN: 'MODAL_CREATE_RECEIPT_TOGGLE_OPEN',
  MODAL_CREATE_RECEIPT_UPDATE_FORM: 'MODAL_CREATE_RECEIPT_UPDATE_FORM',
  MODAL_CREATE_RECEIPT_CHANGE_FORM: 'MODAL_CREATE_RECEIPT_CHANGE_FORM',
  MODAL_CREATE_RECEIPT_UPDATE_VALIDATE: 'MODAL_CREATE_RECEIPT_UPDATE_VALIDATE',

  MODAL_REMOVE_RECEIPT_TOGGLE_OPEN: 'MODAL_REMOVE_RECEIPT_TOGGLE_OPEN',
  MODAL_REMOVE_RECEIPT_UPDATE_DATA: 'MODAL_REMOVE_RECEIPT_UPDATE_DATA',

  MODAL_INACTIVE_RECEIPT_TOGGLE_OPEN: 'MODAL_INACTIVE_RECEIPT_TOGGLE_OPEN',
  MODAL_INACTIVE_RECEIPT_DEBOUNCE: 'MODAL_INACTIVE_RECEIPT_DEBOUNCE',
}