export const facebookResponseContentScriptActions = {
  FILTER_KEYWORD_UPDATE: 'FILTER_KEYWORD_UPDATE',
  SCRIPT_LIST_UPDATE: 'SCRIPT_LIST_UPDATE',
  SCRIPT_LOADING_UPDATE: 'SCRIPT_LOADING_UPDATE',
  DETAIL_UPDATE: 'DETAIL_UPDATE',
  DETAIL_RESET: 'DETAIL_RESET',
  DETAIL_CONFIRM_UPDATE: 'DETAIL_CONFIRM_UPDATE',
  DETAIL_MODIFILED_UPDATE: 'DETAIL_MODIFILED_UPDATE',
  DETAIL_LOADING_UPDATE: 'DETAIL_LOADING_UPDATE',
  MODAL_CONFIRM_DELETE_UPDATE: 'MODAL_CONFIRM_DELETE_UPDATE',
  MODAL_CONFIRM_DELETE_LOADING_TOGGLE: 'MODAL_CONFIRM_DELETE_LOADING_TOGGLE',
}
