export const posOrderActions = {
  SET_LOADING: 'SET_LOADING',
  LOAD_STATE: 'LOAD_STATE',
  UPDATE_LEAVE_MODAL_STATUS: 'UPDATE_LEAVE_MODAL_STATUS',
  UPDATE_REMOVE_ORDER_MODAL_STATUS: 'UPDATE_REMOVE_ORDER_MODAL_STATUS',
  UPDATE_BARCODE_STATUS: 'UPDATE_BARCODE_STATUS',
  ORIGIN: 'ORIGIN',
  UPDATE_LIST_POS_ORDERS: 'UPDATE_LIST_POS_ORDERS',
  UPDATE_TAB_ORDERS: 'UPDATE_TAB_ORDERS',

  WAREHOUSE_KEYWORD_UPDATE: 'WAREHOUSE_KEYWORD_UPDATE',
  ORDER_WAREHOUSE_VALUE_UPDATE: 'ORDER_WAREHOUSE_VALUE_UPDATE',

  ORDER_PRODUCT_UPDATE: 'ORDER_PRODUCT_UPDATE',
  UPDATE_PRODUCT_SEARCH_INFO: 'UPDATE_PRODUCT_SEARCH_INFO',
  QUICK_PRODUCT_UPDATE: 'QUICK_PRODUCT_UPDATE',
  QUICK_PRODUCT_TOGGLE_UPDATE: 'QUICK_PRODUCT_TOGGLE_UPDATE',
  UPDATE_STATUS_MODAL_SHORTCUT: 'UPDATE_STATUS_MODAL_SHORTCUT',
  UPDATE_TYPE_VIEW_PRODUCT: 'UPDATE_TYPE_VIEW_PRODUCT',

  //  =================== GROUP PRODUCT ===============

  FILTER_GROUP_PRODUCT_UPDATE: 'FILTER_GROUP_PRODUCT_UPDATE',
  FILTER_GROUP_PRODUCT_UPDATE_LIST_CHILDREN_TWO: 'FILTER_GROUP_PRODUCT_UPDATE_LIST_CHILDREN_TWO',
  FILTER_GROUP_PRODUCT_CHANGE_KEYWORD: 'FILTER_GROUP_PRODUCT_CHANGE_KEYWORD',
  FILTER_GROUP_PRODUCT_CHANGE_ID: 'FILTER_GROUP_PRODUCT_CHANGE_ID',
  FILTER_GROUP_PRODUCT_UPDATE_VALUE: 'FILTER_GROUP_PRODUCT_UPDATE_VALUE',
  FILTER_GROUP_PRODUCT_UPDATE_ACTIVE_VALUE: 'FILTER_GROUP_PRODUCT_UPDATE_ACTIVE_VALUE',

  // ==========  ==========  Right Content ==========  ==========
  RIGHT_CONTENT_UPDATE_PAYMENT_ORDER: 'RIGHT_CONTENT_UPDATE_PAYMENT_ORDER',
  RIGHT_CONTENT_TAB_CHANGE: 'RIGHT_CONTENT_TAB_CHANGE',

  RIGHT_CONTENT_MODAL_SELECT_PAYMENT: 'RIGHT_CONTENT_MODAL_SELECT_PAYMENT',

  RESET_FORM_CREATE_CUSTOMER: 'RESET_FORM_CREATE_CUSTOMER',
  ORDER_CUSTOMER_VALUE_UPDATE: 'ORDER_CUSTOMER_VALUE_UPDATE',
  UPDATE_LIST_CUSTOMER: 'UPDATE_LIST_CUSTOMER',
  FORM_CREATE_CUSTOMER_DISPLAY: 'FORM_CREATE_CUSTOMER_DISPLAY',
  FORM_CUSTOMER_SHOW_MORE: 'FORM_CUSTOMER_SHOW_MORE',
  VALIDATE_FORM_CUSTOMER_UPDATE: 'VALIDATE_FORM_CUSTOMER_UPDATE',
  FORM_NAME_CUSTOMER_UPDATE: 'FORM_NAME_CUSTOMER_UPDATE',
  FORM_PHONE_CUSTOMER_UPDATE: 'FORM_PHONE_CUSTOMER_UPDATE',
  FORM_CODE_CUSTOMER_UPDATE: 'FORM_CODE_CUSTOMER_UPDATE',
  FORM_NOTE_CUSTOMER_UPDATE: 'FORM_NOTE_CUSTOMER_UPDATE',
  FORM_EMAIL_CUSTOMER_UPDATE: 'FORM_EMAIL_CUSTOMER_UPDATE',
  FORM_GROUP_CUSTOMER_UPDATE: 'FORM_GROUP_CUSTOMER_UPDATE',
  FORM_GROUP_CUSTOMER_KEYWORD_UPDATE: 'FORM_GROUP_CUSTOMER_KEYWORD_UPDATE',
  FORM_GENDER_CUSTOMER_UPDATE: 'FORM_GENDER_CUSTOMER_UPDATE',
  SET_CUSTOMER_SUGGEST_ADDRESS: 'SET_CUSTOMER_SUGGEST_ADDRESS',
  FORM_ADDRESS_UPDATE: 'FORM_ADDRESS_UPDATE',
  FORM_ADDRESS_PROVINCE_UPDATE: 'FORM_ADDRESS_PROVINCE_UPDATE',
  FORM_ADDRESS_PROVINCE_KEYWORD_UPDATE: 'FORM_ADDRESS_PROVINCE_KEYWORD_UPDATE',
  FORM_ADDRESS_DISTRICT_UPDATE: 'FORM_ADDRESS_DISTRICT_UPDATE',
  FORM_ADDRESS_DISTRICT_KEYWORD_UPDATE: 'FORM_ADDRESS_DISTRICT_KEYWORD_UPDATE',
  FORM_ADDRESS_WARD_UPDATE: 'FORM_ADDRESS_WARD_UPDATE',
  FORM_ADDRESS_WARD_KEYWORD_UPDATE: 'FORM_ADDRESS_WARD_KEYWORD_UPDATE',
  RIGHT_CONTENT_MODAL_RESPONSE_SUBMIT: 'RIGHT_CONTENT_MODAL_RESPONSE_SUBMIT',

  SET_CREATED_ORDER_ID: 'SET_CREATED_ORDER_ID',
  SET_CREATED_ERROR_SUBMIT: 'SET_CREATED_ERROR_SUBMIT',
  RIGHT_CONTENT_MODAL_OPEN_CONFIRM_ORDER: 'RIGHT_CONTENT_MODAL_OPEN_CONFIRM_ORDER',
  SET_ADDRESS_ORDER: 'SET_ADDRESS_ORDER',
  // ==========  ==========  End Right Content ==========  ==========
}
